export const LOTTO_CONFIG = {
  PRICE: 1000,
  NUMBER_COUNT: 6,
  MIN_NUMBER: 1,
  MAX_NUMBER: 45,
};

export const STATISTICS_CONFIG = {
  RETURN_RATE_MULTIPLIER: 1000,
  RETURN_RATE_DIVISOR: 10,
  DECIMAL_PLACES: 1,
};
